FROM apache/hive:4.0.0

USER root
RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

ADD https://jdbc.postgresql.org/download/postgresql-42.7.4.jar /opt/hive/lib/

RUN mkdir -p /opt/hive/lib && \
    curl -L -o /opt/hive/lib/hadoop-aws-3.3.6.jar \
        https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar && \
    curl -L -o /opt/hive/lib/aws-java-sdk-bundle-1.12.262.jar \
        https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar

RUN chown -R hive:hive /opt/hive/lib/

USER hive